#if !canImport(ObjectiveC)
import XCTest

extension QuestionOntologyGraphProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuestionOntologyGraphProviderTests = [
        ("testQ10", testQ10),
        ("testQ11", testQ11),
        ("testQ12", testQ12),
        ("testQ13", testQ13),
        ("testQ14", testQ14),
        ("testQ15", testQ15),
        ("testQ16", testQ16),
        ("testQ17", testQ17),
        ("testQ18", testQ18),
        ("testQ19", testQ19),
        ("testQ1", testQ1),
        ("testQ20", testQ20),
        ("testQ21", testQ21),
        ("testQ22", testQ22),
        ("testQ2", testQ2),
        ("testQ3", testQ3),
        ("testQ4", testQ4),
        ("testQ5", testQ5),
        ("testQ6", testQ6),
        ("testQ7", testQ7),
        ("testQ8", testQ8),
        ("testQ9", testQ9),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(QuestionOntologyGraphProviderTests.__allTests__QuestionOntologyGraphProviderTests),
    ]
}
#endif
