#if !canImport(ObjectiveC)
import XCTest

extension QuestionOntologyGraphProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuestionOntologyGraphProviderTests = [
        ("testQ1", testQ1),
        ("testQ2", testQ2),
        ("testQ3", testQ3),
        ("testQ4", testQ4),
        ("testQ5", testQ5),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(QuestionOntologyGraphProviderTests.__allTests__QuestionOntologyGraphProviderTests),
    ]
}
#endif
