#if !canImport(ObjectiveC)
import XCTest

extension QuestionOntologyGraphProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuestionOntologyGraphProviderTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(QuestionOntologyGraphProviderTests.__allTests__QuestionOntologyGraphProviderTests),
    ]
}
#endif
